Repository lizardmon/Bookeun-iOS, pull requests merged in 2019-11, with the labels that each got.

#1 Feature Issue Template 추가
  .github/ISSUE_TEMPLATE/feature-issue-template.md
Labels: Review required

#2 Update issue templates
  .github/ISSUE_TEMPLATE/----bug-report-template.md
Labels: Review required

#3 FEAT: 앱 아이콘 Assets 추가
  Bookeun/Assets.xcassets/AppIcon.appiconset/Contents.json
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-40.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-40@3x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-72.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-72@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-76.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-small-50.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-small-50@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-small.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-small@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon-small@3x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/icon@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/notification-icon@2x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/notification-icon@3x.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad.png
  Bookeun/Assets.xcassets/AppIcon.appiconset/notification-icon~ipad@2x.png
Labels: Feature, Review required

#4 FEAT: 앱에서 사용하는 Entity 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Entity/Book.swift
  Bookeun/Entity/Exercise.swift
  Bookeun/Entity/Trainer.swift
Labels: Feature, Review required

#13 FEAT: 프로젝트에서 사용할 BaseView를 추가합니다.
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Base/View.swift
Labels: Feature, Review required

#11 FIX : excluded 콜론 추가
  .swiftlint.yml
  Bookeun.xcodeproj/project.pbxproj
Labels: Review required

#15 FIX : excluded 콜론 추가
  .swiftlint.yml
  Bookeun.xcodeproj/project.pbxproj
Labels: Bug, Review required

#7 FEAT: 스플래시 화면 및 스플래시 이미지 추가
  Bookeun/Assets.xcassets/SplashIcon.imageset/Contents.json
  Bookeun/Assets.xcassets/SplashIcon.imageset/splash.png
  Bookeun/Assets.xcassets/SplashIcon.imageset/splash@2x.png
  Bookeun/Assets.xcassets/SplashIcon.imageset/splash@3x.png
  Bookeun/Base.lproj/LaunchScreen.storyboard
Labels: Feature, Review required

#17 FEAT: UIView에 `addSubviews` funtion 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Base/UIView+Extension.swift
Labels: Feature

#19 FEAT : iOS 버전
  Bookeun.xcodeproj/project.pbxproj
Labels: Review required

#18 FEAT : Swift Lint Yml 수정
  .swiftlint.yml
Labels: Review required

#21 FEAT : 폴더 구조 통일
  Bookeun.xcodeproj/project.pbxproj
Labels: Review required

#23 FEAT : Back Button Image 추가
  Bookeun/Assets.xcassets/btnBack.imageset/Contents.json
  Bookeun/Assets.xcassets/btnBack.imageset/btnBack.pdf
Labels: Review required

#22 FEAT: 광역적으로 사용될 `ErrorView`, `ErrorViewController` 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/AppDelegate.swift
  Bookeun/Base/ViewController.swift
  Bookeun/Entity/Exercise.swift
  Bookeun/Presentation/Error/ErrorView.swift
  Bookeun/Presentation/Error/ErrorViewController.swift
  Bookeun/RootWindow.swift
Labels: Feature, Review required

#24 FEAT: Bookeun Network Repository 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Entity/Exercise.swift
  Bookeun/Entity/ExerciseCategory.swift
  Bookeun/Network/BookeunAPI.swift
  Bookeun/Network/NetworkReposity.swift
  Bookeun/Repository/BookRepository.swift
  Bookeun/Repository/ExerciseRepository.swift
  Bookeun/Repository/RepositoryContainer.swift
  Bookeun/Repository/TrainerRepository.swift
Labels: Feature, Review required

#28 FEAT: Add Store 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Entity/ExerciseWithCount.swift
  Bookeun/Entity/Store.swift
Labels: Review required

#29 FEAT: 바코드 인식화면 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Base/UIView+Extension.swift
  Bookeun/Info.plist
  Bookeun/Presentation/Barcode/BarcodePresenter.swift
  Bookeun/Presentation/Barcode/BarcodeView.swift
  Bookeun/Presentation/Barcode/BarcodeViewController.swift
Labels: Feature, Review required

#27 FEAT: Select Exercise View 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Assets.xcassets/btnCheckColor.imageset/Contents.json
  Bookeun/Assets.xcassets/btnCheckColor.imageset/btnCheckColor.pdf
  Bookeun/Assets.xcassets/btnCheckColorCopy.imageset/Contents.json
  Bookeun/Assets.xcassets/btnCheckColorCopy.imageset/btnCheckColorCopy.pdf
  Bookeun/Assets.xcassets/btnPlus.imageset/Contents.json
  Bookeun/Assets.xcassets/btnPlus.imageset/btnPlus (1).pdf
  Bookeun/Assets.xcassets/iconCart.imageset/Contents.json
  Bookeun/Assets.xcassets/iconCart.imageset/iconCart.pdf
  Bookeun/Assets.xcassets/shadow (1).imageset/Contents.json
  Bookeun/Assets.xcassets/shadow (1).imageset/shadow (1).pdf
  Bookeun/Assets.xcassets/shadow.imageset/Contents.json
  Bookeun/Assets.xcassets/shadow.imageset/shadow.pdf
  Bookeun/Assets.xcassets/ssSss.imageset/Contents.json
  Bookeun/Assets.xcassets/ssSss.imageset/ssSss (1).pdf
  Bookeun/Base/ViewController.swift
  Bookeun/Presentation/ExerciseList/ExerciseList.storyboard
  Bookeun/Presentation/ExerciseList/ExerciseListViewController.swift
  Bookeun/Presentation/ExerciseList/ExerciseListViewControllerPresenter.swift
  Bookeun/Presentation/ExerciseList/View/ExerciseListViewCell.swift
  Bookeun/Presentation/SelectExercise/SelectExercise.storyboard
  Bookeun/Presentation/SelectExercise/SelectExerciseViewController.swift
  Bookeun/Presentation/SelectExercise/SelectExerciseViewControllerPresenter.swift
  Bookeun/Presentation/SelectExercise/View/SelectExerciseViewCell.swift
  Bookeun/RootWindow.swift
  Bookeun/Util/CenterCollectionLayout.swift
  Bookeun/Util/Nameable.swift
Labels: Review required

#31 FEAT: Add Navtaion Bar [공통]
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Base/ViewController.swift
  Bookeun/RootWindow.swift
  Bookeun/Util/Extension/UIColor.swift
Labels: Review required
