Repository lizardmon/Bookeun-iOS, pull requests merged in 2020-01, with the labels that each got.

#36 [FEAT] 운동 결과 화면 및 ResultPresenter 추가
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Assets.xcassets/ResultMessageBox.imageset/Contents.json
  Bookeun/Assets.xcassets/ResultMessageBox.imageset/invalidName.png
  Bookeun/Assets.xcassets/ResultMessageBox.imageset/invalidName@2x.png
  Bookeun/Assets.xcassets/ResultMessageBox.imageset/invalidName@3x.png
  Bookeun/Assets.xcassets/ResultTrainerIcon.imageset/Contents.json
  Bookeun/Assets.xcassets/ResultTrainerIcon.imageset/invalidName.png
  Bookeun/Assets.xcassets/ResultTrainerIcon.imageset/invalidName@2x.png
  Bookeun/Assets.xcassets/ResultTrainerIcon.imageset/invalidName@3x.png
  Bookeun/Entity/Store.swift
  Bookeun/Presentation/Result/ResultPresenter.swift
  Bookeun/Presentation/Result/ResultViewController.swift
  Bookeun/Presentation/Result/SubResultView.swift
Labels: Feature, Review required

#38 [FEAT] 책 등록 정보 뷰 구현
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Presentation/Barcode/BarcodeViewController.swift
  Bookeun/Presentation/RegisterBook/RegisterBookPresenter.swift
  Bookeun/Presentation/RegisterBook/RegisterBookViewController.storyboard
  Bookeun/Presentation/RegisterBook/RegisterBookViewController.swift
Labels: Feature, Review required

#37 FEAT: save exercistList at store
  Bookeun/Entity/Exercise/ExerciseWithCount.swift
  Bookeun/Presentation/ExerciseList/ExerciseList.storyboard
  Bookeun/Presentation/ExerciseList/ExerciseListViewController.swift
  Bookeun/Presentation/ExerciseList/ExerciseListViewControllerPresenter.swift
  Bookeun/Presentation/ExerciseList/View/ExerciseListViewCell.swift
  Bookeun/Presentation/SelectExercise/SelectExercise.storyboard
  Bookeun/Presentation/SelectExercise/SelectExerciseViewController.swift
  Bookeun/Presentation/SelectExercise/View/SelectExerciseViewCell.swift
Labels: Feature, Review required

#39 [FEAT] 운동 후에 브레이크 타임뷰 연결
  .swiftlint.yml
  Bookeun.xcodeproj/project.pbxproj
  Bookeun/Presentation/BreakeTime/BreakeTimeViewController.swift
  Bookeun/Presentation/Exercise/BreakDelegate.swift
  Bookeun/Presentation/Exercise/ExercisePresenter.swift
  Bookeun/Presentation/Exercise/ExerciseViewController.storyboard
  Bookeun/Presentation/Exercise/ExerciseViewController.swift
Labels: Review required

#40 FEAT & FIX : overall app flow
  Bookeun/Entity/Book.swift
  Bookeun/Presentation/Barcode/BarcodeViewController.swift
  Bookeun/Presentation/BreakeTime/BreakeTimePresenter.swift
  Bookeun/Presentation/BreakeTime/BreakeTimeViewController.swift
  Bookeun/Presentation/Exercise/ExercisePresenter.swift
  Bookeun/Presentation/Exercise/ExerciseViewController.swift
  Bookeun/Presentation/ExerciseList/ExerciseListViewController.swift
  Bookeun/Presentation/RegisterBook/RegisterBookPresenter.swift
  Bookeun/Presentation/RegisterBook/RegisterBookViewController.swift
  Bookeun/Presentation/Result/ResultViewController.swift
  Bookeun/Presentation/SelectExercise/SelectExerciseViewController.swift
  Bookeun/Presentation/Trainer/TrainerSelectViewController.swift
Labels: Update

#43 BUGFIX - UI 잡히는 타이밍 이슈 수정 및 중복으로 텍스트 들어간 부분 수정
  Bookeun/Base/ViewController.swift
  Bookeun/Presentation/ExerciseList/ExerciseListViewController.swift
  Bookeun/Presentation/ExerciseList/ExerciseListViewControllerPresenter.swift
  Bookeun/Presentation/ExerciseList/View/ExerciseListViewCell.swift
  Bookeun/Presentation/RegisterBook/RegisterBookViewController.swift
  Bookeun/Presentation/SelectExercise/SelectExerciseViewController.swift
Labels: Bug, Review required

#42 [FEAT] 결과 화면에 `finishButton` 추가
  Bookeun/Presentation/Result/ResultViewController.swift
Labels: Feature, Review required
